AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Health AI API Platform (Serverless)
Globals:
  Function:
    Timeout: 10
Resources:
  HealthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SmartHealthTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: recordId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: recordId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors: "'*'"
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: register_user
      Handler: register_user.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HealthTable
      Environment:
        Variables:
          TABLE_NAME: !Ref HealthTable
      Events:
        RegisterApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user/register
            Method: post
  LogHealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: log_health
      Handler: log_health.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref HealthTable
      Environment:
        Variables:
          TABLE_NAME: !Ref HealthTable
      Events:
        LogApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health/log
            Method: post
  InsightsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get_insights
      Handler: get_insights.lambda_handler
      Runtime: python3.11
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref HealthTable
      Environment:
        Variables:
          TABLE_NAME: !Ref HealthTable
      Events:
        InsightsApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health/insights
            Method: get
Outputs:
  ApiUrl:
    Description: "API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
